/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'countryOfInterest' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'country' : IDL.Text,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'authorEmail' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'approved' : IDL.Bool,
  'parentId' : IDL.Opt(IDL.Nat),
  'postId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'approveComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getApprovedComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getPendingCommentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'rejectComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitComment' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'countryOfInterest' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'country' : IDL.Text,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'authorEmail' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'approved' : IDL.Bool,
    'parentId' : IDL.Opt(IDL.Nat),
    'postId' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'approveComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getApprovedComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getPendingCommentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'rejectComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitComment' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };