/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const FileAttachment = IDL.Record({
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const ContactSubmissionV3 = IDL.Record({
  'attachedFiles' : IDL.Vec(FileAttachment),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'serviceOfInterest' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'preferredContactMethod' : IDL.Opt(IDL.Text),
  'countryOfInterest' : IDL.Text,
  'privacyConsent' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'country' : IDL.Text,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'editBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmissionV3))],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'submitContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Vec(FileAttachment),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const FileAttachment = IDL.Record({
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const ContactSubmissionV3 = IDL.Record({
    'attachedFiles' : IDL.Vec(FileAttachment),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'serviceOfInterest' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'preferredContactMethod' : IDL.Opt(IDL.Text),
    'countryOfInterest' : IDL.Text,
    'privacyConsent' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'country' : IDL.Text,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'editBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmissionV3))],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'submitContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Vec(FileAttachment),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };