/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedDate' : Time,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Comment {
  'id' : bigint,
  'content' : string,
  'authorEmail' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'approved' : boolean,
  'parentId' : [] | [bigint],
  'postId' : string,
}
export interface ContactSubmission {
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phoneNumber' : string,
  'countryOfInterest' : string,
}
export interface Testimonial {
  'country' : string,
  'clientName' : string,
  'quote' : string,
  'photoUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'approveComment' : ActorMethod<[bigint], boolean>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'editBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
  'editComment' : ActorMethod<[bigint, string], boolean>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getApprovedComments' : ActorMethod<[string], Array<Comment>>,
  'getBlogPostById' : ActorMethod<[bigint], BlogPost>,
  'getPendingCommentCount' : ActorMethod<[], bigint>,
  'getPendingComments' : ActorMethod<[], Array<Comment>>,
  'rejectComment' : ActorMethod<[bigint], boolean>,
  'submitComment' : ActorMethod<
    [string, [] | [bigint], string, string, string],
    bigint
  >,
  'submitContact' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];