/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : Time,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'authorEmail' : IDL.Text,
  'edited' : IDL.Bool,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'approved' : IDL.Bool,
  'rejected' : IDL.Bool,
  'parentId' : IDL.Opt(IDL.Text),
  'postId' : IDL.Text,
});
export const FileAttachment = IDL.Record({
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const ContactSubmissionV3 = IDL.Record({
  'attachedFiles' : IDL.Vec(FileAttachment),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'serviceOfInterest' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
  'preferredContactMethod' : IDL.Opt(IDL.Text),
  'countryOfInterest' : IDL.Text,
  'privacyConsent' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'country' : IDL.Text,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const SectionField = IDL.Record({
  'key' : IDL.Text,
  'value' : IDL.Text,
});
export const PageSection = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'sectionType' : IDL.Text,
  'fields' : IDL.Vec(SectionField),
});
export const WebsitePage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'updatedAt' : IDL.Int,
  'isDefault' : IDL.Bool,
  'sections' : IDL.Vec(PageSection),
});
export const NavMenuItem = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'text' : IDL.Text,
});
export const GlobalConfig = IDL.Record({
  'siteTitle' : IDL.Text,
  'logoMediaId' : IDL.Opt(IDL.Nat),
  'navigationMenu' : IDL.Vec(NavMenuItem),
  'updatedAt' : IDL.Int,
  'contactEmail' : IDL.Text,
  'footerContent' : IDL.Text,
  'contactAddress' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Nat,
  'base64Data' : IDL.Text,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const PageVersionSummary = IDL.Record({
  'version' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sectionCount' : IDL.Nat,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(PageVersionSummary),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'approveComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createWebsitePage' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Nat], [Result_1], []),
  'deleteWebsitePage' : IDL.Func([IDL.Nat], [Result_1], []),
  'editBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'editWebsitePage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result_1], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getAllContacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmissionV3))],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllWebsitePages' : IDL.Func([], [IDL.Vec(WebsitePage)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getCommentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getGlobalConfig' : IDL.Func([], [IDL.Opt(GlobalConfig)], ['query']),
  'getMediaLibrary' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getPageVersions' : IDL.Func([IDL.Text], [Result_2], ['query']),
  'getPendingComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getRejectedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getUnreadApplicationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWebsitePageById' : IDL.Func([IDL.Nat], [IDL.Opt(WebsitePage)], ['query']),
  'markApplicationsAsRead' : IDL.Func([], [], []),
  'rejectComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'restorePageVersion' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
  'savePageSections' : IDL.Func(
      [IDL.Nat, IDL.Vec(PageSection)],
      [Result_1],
      [],
    ),
  'submitComment' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitContact' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Vec(FileAttachment),
      ],
      [],
      [],
    ),
  'unapproveComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateGlobalConfig' : IDL.Func([GlobalConfig], [Result_1], []),
  'uploadMediaItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : Time,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'authorEmail' : IDL.Text,
    'edited' : IDL.Bool,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'approved' : IDL.Bool,
    'rejected' : IDL.Bool,
    'parentId' : IDL.Opt(IDL.Text),
    'postId' : IDL.Text,
  });
  const FileAttachment = IDL.Record({
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const ContactSubmissionV3 = IDL.Record({
    'attachedFiles' : IDL.Vec(FileAttachment),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'serviceOfInterest' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
    'preferredContactMethod' : IDL.Opt(IDL.Text),
    'countryOfInterest' : IDL.Text,
    'privacyConsent' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'country' : IDL.Text,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const SectionField = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const PageSection = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'sectionType' : IDL.Text,
    'fields' : IDL.Vec(SectionField),
  });
  const WebsitePage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'updatedAt' : IDL.Int,
    'isDefault' : IDL.Bool,
    'sections' : IDL.Vec(PageSection),
  });
  const NavMenuItem = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'text' : IDL.Text,
  });
  const GlobalConfig = IDL.Record({
    'siteTitle' : IDL.Text,
    'logoMediaId' : IDL.Opt(IDL.Nat),
    'navigationMenu' : IDL.Vec(NavMenuItem),
    'updatedAt' : IDL.Int,
    'contactEmail' : IDL.Text,
    'footerContent' : IDL.Text,
    'contactAddress' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Nat,
    'base64Data' : IDL.Text,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const PageVersionSummary = IDL.Record({
    'version' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sectionCount' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(PageVersionSummary),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'approveComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createWebsitePage' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Nat], [Result_1], []),
    'deleteWebsitePage' : IDL.Func([IDL.Nat], [Result_1], []),
    'editBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'editWebsitePage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result_1], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getAllContacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ContactSubmissionV3))],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllWebsitePages' : IDL.Func([], [IDL.Vec(WebsitePage)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getCommentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getGlobalConfig' : IDL.Func([], [IDL.Opt(GlobalConfig)], ['query']),
    'getMediaLibrary' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getPageVersions' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'getPendingComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getRejectedComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getUnreadApplicationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWebsitePageById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WebsitePage)],
        ['query'],
      ),
    'markApplicationsAsRead' : IDL.Func([], [], []),
    'rejectComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'restorePageVersion' : IDL.Func([IDL.Text, IDL.Nat], [Result_1], []),
    'savePageSections' : IDL.Func(
        [IDL.Nat, IDL.Vec(PageSection)],
        [Result_1],
        [],
      ),
    'submitComment' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitContact' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Vec(FileAttachment),
        ],
        [],
        [],
      ),
    'unapproveComment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateGlobalConfig' : IDL.Func([GlobalConfig], [Result_1], []),
    'uploadMediaItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };