/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedDate' : Time,
  'author' : string,
  'summary' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface ContactSubmissionV3 {
  'attachedFiles' : Array<FileAttachment>,
  'fullName' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'serviceOfInterest' : [] | [string],
  'phoneNumber' : string,
  'preferredContactMethod' : [] | [string],
  'countryOfInterest' : string,
  'privacyConsent' : boolean,
}
export interface FileAttachment {
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'fileUrl' : string,
}
export interface Testimonial {
  'country' : string,
  'clientName' : string,
  'quote' : string,
  'photoUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'editBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContacts' : ActorMethod<[], Array<[bigint, ContactSubmissionV3]>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPostById' : ActorMethod<[bigint], BlogPost>,
  'submitContact' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      [] | [string],
      boolean,
      Array<FileAttachment>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];