/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PageVersionSummary {
    version: bigint;
    timestamp: bigint;
    sectionCount: bigint;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    publishedDate: Time;
    author: string;
    summary: string;
    imageUrl: string;
    category: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: Array<PageVersionSummary>;
} | {
    __kind__: "err";
    err: string;
};
export type Time = bigint;
export interface NavMenuItem {
    id: bigint;
    url: string;
    order: bigint;
    text: string;
}
export interface Comment {
    id: string;
    content: string;
    authorEmail: string;
    edited: boolean;
    createdAt: bigint;
    authorName: string;
    approved: boolean;
    rejected: boolean;
    parentId?: string;
    postId: string;
}
export interface PageSection {
    id: bigint;
    order: bigint;
    sectionType: string;
    fields: Array<SectionField>;
}
export interface MediaItem {
    id: bigint;
    base64Data: string;
    mimeType: string;
    filename: string;
    uploadedAt: bigint;
}
export interface SectionField {
    key: string;
    value: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface WebsitePage {
    id: bigint;
    title: string;
    createdAt: bigint;
    slug: string;
    updatedAt: bigint;
    isDefault: boolean;
    sections: Array<PageSection>;
}
export interface FileAttachment {
    fileName: string;
    fileSize: bigint;
    fileType: string;
    fileUrl: string;
}
export type Result = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface GlobalConfig {
    siteTitle: string;
    logoMediaId?: bigint;
    navigationMenu: Array<NavMenuItem>;
    updatedAt: bigint;
    contactEmail: string;
    footerContent: string;
    contactAddress: string;
    contactPhone: string;
}
export interface ContactSubmissionV3 {
    attachedFiles: Array<FileAttachment>;
    fullName: string;
    email: string;
    message: string;
    timestamp: Time;
    serviceOfInterest?: string;
    phoneNumber: string;
    preferredContactMethod?: string;
    countryOfInterest: string;
    privacyConsent: boolean;
}
export interface Testimonial {
    country: string;
    clientName: string;
    quote: string;
    photoUrl: string;
}
export interface backendInterface {
    addBlogPost(title: string, summary: string, content: string, author: string, imageUrl: string, category: string): Promise<void>;
    approveComment(commentId: string): Promise<boolean>;
    createWebsitePage(title: string, slug: string): Promise<Result>;
    deleteBlogPost(id: bigint): Promise<void>;
    deleteComment(commentId: string): Promise<boolean>;
    deleteContact(id: bigint): Promise<void>;
    deleteMediaItem(id: bigint): Promise<Result_1>;
    deleteWebsitePage(id: bigint): Promise<Result_1>;
    editBlogPost(id: bigint, title: string, summary: string, content: string, author: string, imageUrl: string, category: string): Promise<void>;
    editComment(commentId: string, newContent: string): Promise<boolean>;
    editWebsitePage(id: bigint, title: string, slug: string): Promise<Result_1>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllComments(): Promise<Array<Comment>>;
    getAllContacts(): Promise<Array<[bigint, ContactSubmissionV3]>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAllWebsitePages(): Promise<Array<WebsitePage>>;
    getBlogPostById(id: bigint): Promise<BlogPost>;
    getCommentCount(): Promise<bigint>;
    getCommentsForPost(postId: string): Promise<Array<Comment>>;
    getGlobalConfig(): Promise<GlobalConfig | null>;
    getMediaLibrary(): Promise<Array<MediaItem>>;
    getPageVersions(slug: string): Promise<Result_2>;
    getPendingComments(): Promise<Array<Comment>>;
    getRejectedComments(): Promise<Array<Comment>>;
    getUnreadApplicationCount(): Promise<bigint>;
    getWebsitePageById(id: bigint): Promise<WebsitePage | null>;
    markApplicationsAsRead(): Promise<void>;
    rejectComment(commentId: string): Promise<boolean>;
    restorePageVersion(slug: string, version: bigint): Promise<Result_1>;
    savePageSections(pageId: bigint, sections: Array<PageSection>): Promise<Result_1>;
    submitComment(postId: string, parentId: string | null, authorName: string, authorEmail: string, content: string): Promise<string>;
    submitContact(fullName: string, phoneNumber: string, email: string, countryOfInterest: string, serviceOfInterest: string | null, message: string, preferredContactMethod: string | null, privacyConsent: boolean, attachedFiles: Array<FileAttachment>): Promise<void>;
    unapproveComment(commentId: string): Promise<boolean>;
    updateGlobalConfig(config: GlobalConfig): Promise<Result_1>;
    uploadMediaItem(filename: string, mimeType: string, base64Data: string): Promise<Result>;
}
import type { Comment as _Comment, ContactSubmissionV3 as _ContactSubmissionV3, FileAttachment as _FileAttachment, GlobalConfig as _GlobalConfig, NavMenuItem as _NavMenuItem, PageVersionSummary as _PageVersionSummary, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Time as _Time, WebsitePage as _WebsitePage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveComment(arg0);
            return result;
        }
    }
    async createWebsitePage(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createWebsitePage(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWebsitePage(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteContact(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWebsitePage(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWebsitePage(arg0);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWebsitePage(arg0);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async editBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async editComment(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editComment(arg0, arg1);
            return result;
        }
    }
    async editWebsitePage(arg0: bigint, arg1: string, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.editWebsitePage(arg0, arg1, arg2);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWebsitePage(arg0, arg1, arg2);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContacts(): Promise<Array<[bigint, ContactSubmissionV3]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAllWebsitePages(): Promise<Array<WebsitePage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWebsitePages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWebsitePages();
            return result;
        }
    }
    async getBlogPostById(arg0: bigint): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return result;
        }
    }
    async getCommentCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentCount();
            return result;
        }
    }
    async getCommentsForPost(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPost(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPost(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalConfig(): Promise<GlobalConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalConfig();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalConfig();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaLibrary(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaLibrary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaLibrary();
            return result;
        }
    }
    async getPageVersions(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageVersions(arg0);
                return from_candid_Result_2_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageVersions(arg0);
            return from_candid_Result_2_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingComments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingComments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRejectedComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRejectedComments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRejectedComments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadApplicationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadApplicationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadApplicationCount();
            return result;
        }
    }
    async getWebsitePageById(arg0: bigint): Promise<WebsitePage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsitePageById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsitePageById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async markApplicationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markApplicationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markApplicationsAsRead();
            return result;
        }
    }
    async rejectComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectComment(arg0);
            return result;
        }
    }
    async restorePageVersion(arg0: string, arg1: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.restorePageVersion(arg0, arg1);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restorePageVersion(arg0, arg1);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePageSections(arg0: bigint, arg1: Array<PageSection>): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.savePageSections(arg0, arg1);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePageSections(arg0, arg1);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitComment(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComment(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComment(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string, arg6: string | null, arg7: boolean, arg8: Array<FileAttachment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async unapproveComment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unapproveComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unapproveComment(arg0);
            return result;
        }
    }
    async updateGlobalConfig(arg0: GlobalConfig): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGlobalConfig(to_candid_GlobalConfig_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGlobalConfig(to_candid_GlobalConfig_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadMediaItem(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMediaItem(arg0, arg1, arg2);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMediaItem(arg0, arg1, arg2);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Comment_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ContactSubmissionV3_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactSubmissionV3): ContactSubmissionV3 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_GlobalConfig_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlobalConfig): GlobalConfig {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GlobalConfig]): GlobalConfig | null {
    return value.length === 0 ? null : from_candid_GlobalConfig_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WebsitePage]): WebsitePage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attachedFiles: Array<_FileAttachment>;
    fullName: string;
    email: string;
    message: string;
    timestamp: _Time;
    serviceOfInterest: [] | [string];
    phoneNumber: string;
    preferredContactMethod: [] | [string];
    countryOfInterest: string;
    privacyConsent: boolean;
}): {
    attachedFiles: Array<FileAttachment>;
    fullName: string;
    email: string;
    message: string;
    timestamp: Time;
    serviceOfInterest?: string;
    phoneNumber: string;
    preferredContactMethod?: string;
    countryOfInterest: string;
    privacyConsent: boolean;
} {
    return {
        attachedFiles: value.attachedFiles,
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        serviceOfInterest: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.serviceOfInterest)),
        phoneNumber: value.phoneNumber,
        preferredContactMethod: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.preferredContactMethod)),
        countryOfInterest: value.countryOfInterest,
        privacyConsent: value.privacyConsent
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    logoMediaId: [] | [bigint];
    navigationMenu: Array<_NavMenuItem>;
    updatedAt: bigint;
    contactEmail: string;
    footerContent: string;
    contactAddress: string;
    contactPhone: string;
}): {
    siteTitle: string;
    logoMediaId?: bigint;
    navigationMenu: Array<NavMenuItem>;
    updatedAt: bigint;
    contactEmail: string;
    footerContent: string;
    contactAddress: string;
    contactPhone: string;
} {
    return {
        siteTitle: value.siteTitle,
        logoMediaId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.logoMediaId)),
        navigationMenu: value.navigationMenu,
        updatedAt: value.updatedAt,
        contactEmail: value.contactEmail,
        footerContent: value.footerContent,
        contactAddress: value.contactAddress,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    authorEmail: string;
    edited: boolean;
    createdAt: bigint;
    authorName: string;
    approved: boolean;
    rejected: boolean;
    parentId: [] | [string];
    postId: string;
}): {
    id: string;
    content: string;
    authorEmail: string;
    edited: boolean;
    createdAt: bigint;
    authorName: string;
    approved: boolean;
    rejected: boolean;
    parentId?: string;
    postId: string;
} {
    return {
        id: value.id,
        content: value.content,
        authorEmail: value.authorEmail,
        edited: value.edited,
        createdAt: value.createdAt,
        authorName: value.authorName,
        approved: value.approved,
        rejected: value.rejected,
        parentId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.parentId)),
        postId: value.postId
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ContactSubmissionV3]): [bigint, ContactSubmissionV3] {
    return [
        value[0],
        from_candid_ContactSubmissionV3_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_PageVersionSummary>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<PageVersionSummary>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ContactSubmissionV3]>): Array<[bigint, ContactSubmissionV3]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
function to_candid_GlobalConfig_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlobalConfig): _GlobalConfig {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    logoMediaId?: bigint;
    navigationMenu: Array<NavMenuItem>;
    updatedAt: bigint;
    contactEmail: string;
    footerContent: string;
    contactAddress: string;
    contactPhone: string;
}): {
    siteTitle: string;
    logoMediaId: [] | [bigint];
    navigationMenu: Array<_NavMenuItem>;
    updatedAt: bigint;
    contactEmail: string;
    footerContent: string;
    contactAddress: string;
    contactPhone: string;
} {
    return {
        siteTitle: value.siteTitle,
        logoMediaId: value.logoMediaId ? candid_some(value.logoMediaId) : candid_none(),
        navigationMenu: value.navigationMenu,
        updatedAt: value.updatedAt,
        contactEmail: value.contactEmail,
        footerContent: value.footerContent,
        contactAddress: value.contactAddress,
        contactPhone: value.contactPhone
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
